{
 "title": "MAP NODE DASHBOARD",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "TOTAL NUMBER OF REQUESTS SERVED",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MAP REQUESTS",
   "type": "graph",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "number of requests",
     "measurement": "nginx",
     "select": [
      [
       { "params": [ "requests" ], "type": "field" },
       { "params": [ "10s" ], "type": "derivative" }
      ]
     ]
    }
   ]
  }
 ]
}