{
 "title": "Map3 Local Node",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "rp",
    "label": "Retention Policy",
    "query": "select rp from forever.rp_config where $__to - $__from > \"start\" and $__to - $__from < \"end\""
   }
  ]
 },
 "panels": [
  {
   "title": "TOTAL NUMBER OF REQUESTS SERVED",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "measurement": "geodata",
     "query": "SELECT sum(\"count\") FROM \"$rp\".\"geodata\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 8, "x": 7, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "query": "SELECT mean(\"usage_user\") FROM \"$rp\".\"cpu\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "MEMORY USAGE",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "REQUESTS",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of Requests",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "geodata",
     "query": "SELECT sum(\"count\") FROM \"$rp\".\"geodata\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request From",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "geohash" ], "type": "tag" },
      { "params": [ "city" ], "type": "tag" }
     ],
     "measurement": "geodata",
     "query": "SELECT sum(\"count\") as total FROM \"$rp\".\"geodata\" WHERE $timeFilter GROUP BY \"geohash\", \"city\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  }
 ]
}