# refer: https://github.com/elastic/examples/tree/master/Miscellaneous/docker/full_stack_example

version: "2.3"

services:
  reverse-proxy:
    image: docker.io/map3/caddy:0.618
    restart: always
    ports:
      - 80:80
      - 443:443
    entrypoint: ["/usr/local/bin/caddy", "-conf", "/etc/caddy/prodcaddyfile"]
    volumes:
      #Logs are mounted to a relative path. These are also accessed by Filebeat and consumed by the Nginx module
      - ./log/reverse-proxy/:/var/log/caddy/
      - ./config/caddy/prodcaddyfile:/etc/caddy/prodcaddyfile:ro
      - ./config/caddy/certs/tile-server.pem:/etc/caddy/tile-server.pem:ro
      - ./public_html/:/var/run/caddy/public_html/

  #Filebeat container
  filebeat:
    user: root
    image: docker.io/map3/filebeat:7.1
    volumes:
      #Named volume fsdata. This is used to persist the registry file between restarts, so to avoid data duplication
      - fbdata:/usr/share/filebeat/data
      #Mount nginx log directory
      - ./log/reverse-proxy/:/var/log/reverse-proxy/
      #Allows us to report on docker from the hosts information
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "filebeat -e --strict.perms=false -E name=`curl -s http://whatismyip.akamai.com/`"
    restart: on-failure

  influxdb:
    image: docker.io/map3/influxdb:1.7
    restart: always
    volumes:
      - influxdb_data:/var/lib/influxdb

  telegraf:
    image: docker.io/map3/telegraf:1.11
    restart: always
    depends_on:
      - influxdb

  grafana:
    image: docker.io/map3/grafana:6.2
    restart: always
    ports:
      - 3000:3000 # grafana
    entrypoint: /entry.sh
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - telegraf

  geostat:
    image: docker.io/map3/go-geostat:1.0
    restart: always
    volumes:
      - ./log/reverse-proxy/:/var/log/geostat/
      - ./config/go-geostat/geostat.json:/etc/geostat/geostat.json:ro
    depends_on:
      - reverse-proxy

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: docker.io/map3/ouroboros:latest
    environment:
      - CLEANUP=true
      - CLEANUP_UNUSED_VOLUMES=true
      - INTERVAL=100
      - LOG_LEVEL=INFO
      - SELF_UPDATE=true
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  #Filebeat data i.e. registry file
  fbdata:
    driver: local
  influxdb_data:
    driver: local
  grafana_data:
    driver: local
