version: "2.3"

services:
  map3:
    image: map3/deploy-edge-nsa:latest
    build: 
      context: ../
      dockerfile: map3-edge-in-docker/Dockerfile
    ports:
      - 8880:8880
      - 8443:8443
      - 8300:8300
    restart: always
    privileged: true
    volumes:
      - volume_data:/var/lib/docker/

  ouroboros:
    container_name: ouroboros
    hostname: ouroboros
    image: map3/ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=INFO
      - SELF_UPDATE=true
      - IGNORE=mongo postgres mariadb
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  volume_data:
    driver: local